/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ArvorePackger;

import javax.swing.JOptionPane;

/**
 *
 * @author Kcer
 */
public class Organograma extends javax.swing.JFrame {
    
    /**
     * Creates new form Organograma
     */
    public Organograma() {
        initComponents();
        lblAM.setVisible(false);//1
        lblAP.setVisible(false);//2
        lblAv1M.setVisible(false);//3
        lblAvP.setVisible(false);//4
        lblF.setVisible(false);//5
        lblGF.setVisible(false);//6
        lblGM.setVisible(false);//7
        lblGMM.setVisible(false);//8
        lblGMP.setVisible(false);//9
        lblGP.setVisible(false);//10
        lblGPM.setVisible(false);//11
        lblGPP.setVisible(false);//12
        lblM.setVisible(false);//13
        lblMP.setVisible(false);//14
        lblMPM.setVisible(false);//15
        lblNF.setVisible(false);//16
        lblNM.setVisible(false);//17
        lblNMM.setVisible(false);//18
        lblNMP.setVisible(false);//19
        lblNP.setVisible(false);//20
        lblNPM.setVisible(false);//21
        lblNPP.setVisible(false);//22
        lblP.setVisible(false);//23
        lblPM.setVisible(false);//24
        lblPMF.setVisible(false);//25
        lblPMP.setVisible(false);//26
        btnAddF.setVisible(false);//27
        btnAddPP.setVisible(false);//28
        btnAddPM.setVisible(false);//29
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNP = new javax.swing.JLabel();
        lblNM = new javax.swing.JLabel();
        lblNF = new javax.swing.JLabel();
        lblGF = new javax.swing.JLabel();
        lblGM = new javax.swing.JLabel();
        lblGP = new javax.swing.JLabel();
        lblP = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblF = new javax.swing.JLabel();
        lblPMP = new javax.swing.JLabel();
        lblMPM = new javax.swing.JLabel();
        lblPMF = new javax.swing.JLabel();
        lblNMP = new javax.swing.JLabel();
        lblGMP = new javax.swing.JLabel();
        lblAM = new javax.swing.JLabel();
        lblNMM = new javax.swing.JLabel();
        lblGMM = new javax.swing.JLabel();
        lblAv1M = new javax.swing.JLabel();
        lblNPP = new javax.swing.JLabel();
        lblGPP = new javax.swing.JLabel();
        lblAP = new javax.swing.JLabel();
        lblNPM = new javax.swing.JLabel();
        lblGPM = new javax.swing.JLabel();
        lblAvP = new javax.swing.JLabel();
        lblPM = new javax.swing.JLabel();
        lblMP = new javax.swing.JLabel();
        btnAddPP = new javax.swing.JButton();
        btnAddPM = new javax.swing.JButton();
        btnAddF = new javax.swing.JButton();
        btnAddFamilia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNP.setText("NOME");
        jPanel1.add(lblNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        lblNM.setText("NOME");
        jPanel1.add(lblNM, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        lblNF.setText("NOME");
        jPanel1.add(lblNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        lblGF.setText("FILHO");
        jPanel1.add(lblGF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        lblGM.setText("MÃE");
        jPanel1.add(lblGM, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        lblGP.setText("PAI");
        jPanel1.add(lblGP, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        lblP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EsquemaPAI.PNG"))); // NOI18N
        jPanel1.add(lblP, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 220, -1, -1));

        lblM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EsquemaMAE.PNG"))); // NOI18N
        jPanel1.add(lblM, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 220, -1, -1));

        lblF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EsquemaPAI.PNG"))); // NOI18N
        jPanel1.add(lblF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        lblPMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LigacaoPAIS_AVOSE_ESQUERDA.PNG"))); // NOI18N
        jPanel1.add(lblPMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        lblMPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LigacaoPAIS_AVOSE_DIREITA.png"))); // NOI18N
        jPanel1.add(lblMPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, -1, -1));

        lblPMF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LigacaoPAIMAEFILHO.PNG"))); // NOI18N
        jPanel1.add(lblPMF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));

        lblNMP.setText("NOME");
        jPanel1.add(lblNMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        lblGMP.setText("AVÔ");
        jPanel1.add(lblGMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, -1, -1));

        lblAM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EsquemaPAI.PNG"))); // NOI18N
        jPanel1.add(lblAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(648, 130, -1, -1));

        lblNMM.setText("NOME");
        jPanel1.add(lblNMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, -1, -1));

        lblGMM.setText("AVÓ");
        jPanel1.add(lblGMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, -1, -1));

        lblAv1M.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EsquemaMAE.PNG"))); // NOI18N
        jPanel1.add(lblAv1M, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 130, -1, -1));

        lblNPP.setText("NOME");
        jPanel1.add(lblNPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        lblGPP.setText("AVÔ");
        jPanel1.add(lblGPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        lblAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EsquemaPAI.PNG"))); // NOI18N
        jPanel1.add(lblAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        lblNPM.setText("NOME");
        jPanel1.add(lblNPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        lblGPM.setText("AVÓ");
        jPanel1.add(lblGPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        lblAvP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/EsquemaMAE.PNG"))); // NOI18N
        jPanel1.add(lblAvP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lblPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LigacaoAVOS_ESQUERDA.PNG"))); // NOI18N
        jPanel1.add(lblPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 150, -1, -1));

        lblMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LigacaoAVOS_DIREITA.PNG"))); // NOI18N
        jPanel1.add(lblMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 160, -1, -1));

        btnAddPP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BUTTONADD.png"))); // NOI18N
        btnAddPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPPActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 260, 30, -1));

        btnAddPM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BUTTONADD.png"))); // NOI18N
        btnAddPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPMActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 260, 30, -1));

        btnAddF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BUTTONADD.png"))); // NOI18N
        jPanel1.add(btnAddF, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 30, -1));

        btnAddFamilia.setText("Adicionar Familia");
        btnAddFamilia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFamiliaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(491, Short.MAX_VALUE)
                .addComponent(btnAddFamilia)
                .addGap(457, 457, 457))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddFamilia)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFamiliaActionPerformed
        // TODO add your handling code here:
        String grau, filho, pai, mae;
        filho = JOptionPane.showInputDialog("Nome do Filho? ");
        grau = JOptionPane.showInputDialog("Grau");
        lblNF.setText(filho);//16
        lblGF.setText(grau);//6
        mae =  JOptionPane.showInputDialog("Nome da Mãe? ");
        grau = JOptionPane.showInputDialog("Grau");
        lblNM.setText(mae);//17
        lblGM.setText(grau);//7
        pai =  JOptionPane.showInputDialog("Nome do Pai? ");
        grau = JOptionPane.showInputDialog("Grau");
        lblNP.setText(pai);//20
        lblGP.setText(grau);//10
        
        if (filho != null){
            lblF.setVisible(true);//5
            lblNF.setVisible(true);//16
            lblGF.setVisible(true);//6
            btnAddF.setVisible(true);//27
        } 
        if(mae != null){
            lblM.setVisible(true);//13
            lblNM.setVisible(true);//17
            lblGM.setVisible(true);//7
            btnAddPM.setVisible(true);//29
        }
        if (pai != null){
            lblP.setVisible(true);//23
            lblNP.setVisible(true);//20
            lblGP.setVisible(true);//10
            btnAddPP.setVisible(true);//28
        }
        if (pai!= null && mae!=null){
            lblPMF.setVisible(true);//25
        }
    }//GEN-LAST:event_btnAddFamiliaActionPerformed

    private void btnAddPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPPActionPerformed
        // TODO add your handling code here:
        String avo11, avo12, grau;
        avo11 = JOptionPane.showInputDialog("Nome?");
        grau = JOptionPane.showInputDialog("Grau");
        lblNPP.setText(avo11);//22
        lblGPP.setText(grau);//12
        avo12 = JOptionPane.showInputDialog("Nome?");
        grau = JOptionPane.showInputDialog("Grau");
        lblNPM.setText(avo12);//21
        lblGPM.setText(grau);//11
        
        if(avo11 != null){
            lblAP.setVisible(true);//2
            lblNPP.setVisible(true);//22
            lblGPP.setVisible(true);//12
            btnAddPP.setVisible(false);//28
        }
        if (avo12 != null){
            lblAvP.setVisible(true);//4
            lblNPM.setVisible(true);//21
            lblGPM.setVisible(true);//11
        }
        if (avo11!= null && avo12 != null){
        lblPMP.setVisible(true);//26
        lblPM.setVisible(true);//24
        }
    }//GEN-LAST:event_btnAddPPActionPerformed

    private void btnAddPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPMActionPerformed
        // TODO add your handling code here:
        String avo11, avo12, grau;
        avo11 = JOptionPane.showInputDialog("Nome?");
        grau = JOptionPane.showInputDialog("Grau");
        lblNMP.setText(avo11);//19
        lblGMP.setText(grau);//9
        avo12 = JOptionPane.showInputDialog("Nome?");
        grau = JOptionPane.showInputDialog("Grau");
        lblNMM.setText(avo12);//18
        lblGMM.setText(grau);//8
        if(avo11 != null){
            lblNMP.setVisible(true);//19
            lblAM.setVisible(true);//1
            lblGMP.setVisible(true);//9
            btnAddPM.setVisible(false);//24
        }
        if (avo12 != null){
            lblAv1M.setVisible(true);//3
            lblNMM.setVisible(true);//18
            lblGMM.setVisible(true);//8
        }
        if (avo11!= null && avo12 != null){
        lblMPM.setVisible(true);//15
        lblMP.setVisible(true);//14
        }
    }//GEN-LAST:event_btnAddPMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Organograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Organograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Organograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Organograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Organograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddF;
    private javax.swing.JButton btnAddFamilia;
    private javax.swing.JButton btnAddPM;
    private javax.swing.JButton btnAddPP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAM;
    private javax.swing.JLabel lblAP;
    private javax.swing.JLabel lblAv1M;
    private javax.swing.JLabel lblAvP;
    private javax.swing.JLabel lblF;
    private javax.swing.JLabel lblGF;
    private javax.swing.JLabel lblGM;
    private javax.swing.JLabel lblGMM;
    private javax.swing.JLabel lblGMP;
    private javax.swing.JLabel lblGP;
    private javax.swing.JLabel lblGPM;
    private javax.swing.JLabel lblGPP;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblMP;
    private javax.swing.JLabel lblMPM;
    private javax.swing.JLabel lblNF;
    private javax.swing.JLabel lblNM;
    private javax.swing.JLabel lblNMM;
    private javax.swing.JLabel lblNMP;
    private javax.swing.JLabel lblNP;
    private javax.swing.JLabel lblNPM;
    private javax.swing.JLabel lblNPP;
    private javax.swing.JLabel lblP;
    private javax.swing.JLabel lblPM;
    private javax.swing.JLabel lblPMF;
    private javax.swing.JLabel lblPMP;
    // End of variables declaration//GEN-END:variables
}
//lblAM.setVisible();
//lblAP.setVisible();
//lblAv1M.setVisible();
//lblAvP.setVisible();
//lblF.setVisible();
//lblGF.setVisible();
//lblGM.setVisible();
//lblGMM.setVisible();
//lblGMP.setVisible();
//lblGP.setVisible();
//lblGPM.setVisible();
//lblGPP.setVisible();
//lblM.setVisible();
//lblMP.setVisible();
//lblMPM.setVisible();
//lblNF.setVisible();
//lblNM.setVisible();
//lblNMM.setVisible();
//lblNMP.setVisible();
//lblNP.setVisible();
//lblNPM.setVisible();
//lblNPP.setVisible();
//lblP.setVisible();
//lblPM.setVisible();
//lblPMF.setVisible();
//lblPMP.setVisible();