-- MySQL Script generated by MySQL Workbench
-- 05/20/18 00:35:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wyp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wyp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wyp` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `wyp` ;

-- -----------------------------------------------------
-- Table `wyp`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyp`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyp`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyp`.`Familia` (
  `id_familia` INT NOT NULL AUTO_INCREMENT,
  `familia` VARCHAR(45) NOT NULL,
  `id_login` INT NOT NULL,
  PRIMARY KEY (`id_familia`),
  INDEX `fk_id_login_idx` (`id_login` ASC),
  CONSTRAINT `fk_id_login`
    FOREIGN KEY (`id_login`)
    REFERENCES `wyp`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyp`.`Nome`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyp`.`Nome` (
  `id_nome` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  `sobrenome` VARCHAR(30) NOT NULL,
  `sexo` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id_nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyp`.`Grau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyp`.`Grau` (
  `id_grau` INT NOT NULL AUTO_INCREMENT,
  `grau` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyp`.`Arvore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyp`.`Arvore` (
  `id_arvore` INT NOT NULL AUTO_INCREMENT,
  `id_familia` INT NOT NULL,
  `id_nome` INT NOT NULL,
  `id_grau` INT NOT NULL,
  `id_nome1` INT NOT NULL,
  PRIMARY KEY (`id_arvore`),
  INDEX `fk_id_familia_idx` (`id_familia` ASC),
  INDEX `fk_id_nome1_idx` (`id_nome` ASC),
  INDEX `fk_id_grau_idx` (`id_grau` ASC),
  INDEX `fk_id_nome1_idx1` (`id_nome1` ASC),
  CONSTRAINT `fk_id_familia`
    FOREIGN KEY (`id_familia`)
    REFERENCES `wyp`.`Familia` (`id_familia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_nome`
    FOREIGN KEY (`id_nome`)
    REFERENCES `wyp`.`Nome` (`id_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_grau`
    FOREIGN KEY (`id_grau`)
    REFERENCES `wyp`.`Grau` (`id_grau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_nome1`
    FOREIGN KEY (`id_nome1`)
    REFERENCES `wyp`.`Nome` (`id_nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
